---
dev_packages:
  - 7zip
  - android-tools
  - android-udev-rules
  - ansible
  - apfs-fuse
  - autoconf
  - automake
  - aws-cli
  - bottom
  - calibre
  - cargo
  - clang18
  - clang18-dev
  - clang18-static
  - cmake
  - coreutils
  - crystal
  - curl-dev
  - debootstrap
  - docker
  - docker-openrc
  - docker-cli-compose
  - docker-rootless-extras
  - efibootmgr
  - eudev-dev
  - exiftool
  - ffmpeg
  - file
  - fish
  - flatpak-builder
  - fuse-exfat
  - g++
  - gcc
  - gcompat
  - git
  - gnupg
  - gnupg-utils
  - helix
  - helix-tree-sitter-vendor
  - imagemagick
  - kernel-hooks
  - libc6-compat
  - libtool
  - libusb-dev
  - libvirt-daemon
  - libvirt-daemon-openrc
  - libzip-dev
  - lynx
  - make
  - msr-tools
  - mtools
  - ncurses
  - ncurses-dev
  - ncurses-static
  - neofetch
  - neovim
  - neovim-lang
  - nmap
  - ntfs-3g
  - openssl-dev
  - pandoc
  - pipx
  - proot
  - protobuf-dev
  - proxychains-ng
  - pugixml
  - pugixml-dev
  - pwgen
  - py3-fpdf
  - py3-lsp-server
  - py3-mypy
  - py3-pip
  - py3-setuptools
  - py3-wheel
  - py3-wheel-pyc
  - python3-dev
  - python3-tkinter
  - qemu-img
  - qemu-modules
  - qemu-system-ppc
  - qemu-system-x86_64
  - ranger
  - ripgrep
  - rust
  - rust-analyzer
  - rustup
  - sbctl
  - sbctl-bash-completion
  - sbctl-fish-completion
  - shadow-subids
  - shards
  - sshpass
  - steam-devices
  - texlive
  - tor
  - transmission-cli
  - tree-sitter-lua
  - tree-sitter-markdown
  - tree-sitter-rust
  - ubuntu-archive-keyring
  - udev-init-scripts
  - udev-init-scripts-openrc
  - unzip
  - v4l-utils-dev
  - virt-install
  - virt-manager
  - xbps
  - xkcdpass
  - xz
  - yazi
  - youtube-dl
  - yt-dlp
  - zed
  - zip
