---
- name: Install openssh
  community.general.apk:
    name: openssh
    state: present

- name: Configure sshd
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd

- name: Enable sshd
  ansible.builtin.service:
    name: sshd
    enabled: true
    runlevel: default
    state: started
